{
 "title": "Andes Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "andes01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "amor02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "andes01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decBps" }
   ],
   "targets": [
    {
     "alias": "andes01 recieved bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02 recieved bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03 recieved bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04 recieved bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05 recieved bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06 recieved bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes01 sent bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " *-1/ 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02 sent bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " *-1/ 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03 sent bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " *-1/ 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04 sent bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " *-1/ 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05 sent bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " *-1/ 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06 sent bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " *-1/ 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "andes01 read IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02 read IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03 read IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04 read IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05 read IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06 read IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes01 write IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1 / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02 write IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1 / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03 write IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1 / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04 write IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1 / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05 write IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1 / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06 write IO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1 / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "andes01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "andes01 used disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes01.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes02 used disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes02.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes03 used disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes03.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes04 used disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes04.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes05 used disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes05.cp.lsst.org" }
     ]
    },
    {
     "alias": "andes06 used disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "andes06.cp.lsst.org" }
     ]
    }
   ]
  }
 ]
}