---
# Source: graylog/charts/elasticsearch/templates/client-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.2
    component: "client"
    heritage: Helm
    release: graylog
  name: graylog-elasticsearch-client
  namespace: it-monitoring
