---
# Source: graylog/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: graylog-web
  namespace: graylog
spec:
  tls:
  - hosts:
    - it-graylog.dev.lsst.org
    secretName: graylog-tls
  rules:
  - host: it-graylog.dev.lsst.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: graylog-web
              port: 
                name: graylog
  