---
# Source: graylog/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graylog
  labels:
    app.kubernetes.io/name: graylog
    helm.sh/chart: graylog-2.1.3
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "graylog"
    app.kubernetes.io/version: "4.2.7"
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
  verbs:
    - get
    - list
    - patch
