---
# Source: graylog/charts/elasticsearch/templates/client-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.2
    component: "client"
    heritage: Helm
    release: graylog
  name: graylog-elasticsearch-client
  namespace: graylog
spec:
  ports:
  - name: http
    port: 9200
    targetPort: http
  selector:
    app: elasticsearch
    component: "client"
    release: graylog
  type: ClusterIP
