---
# Source: graylog/charts/elasticsearch/templates/data-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.2
    component: "data"
    heritage: Helm
    release: graylog
  name: graylog-elasticsearch-data
  namespace: graylog
