#!/usr/bin/env bash
kubectl delete -n it-monitoring -f graylog/secret.yaml
kubectl delete -n it-monitoring -f elasticsearch/configmap.yaml
kubectl delete -n it-monitoring -f mongodb-replicaset/mongodb-init-configmap.yaml
kubectl delete -n it-monitoring -f mongodb-replicaset/mongodb-mongodb-configmap.yaml
kubectl delete -n it-monitoring -f graylog/configmap.yaml
kubectl delete -n it-monitoring -f elasticsearch/client-serviceaccount.yaml
kubectl delete -n it-monitoring -f elasticsearch/data-serviceaccount.yaml
kubectl delete -n it-monitoring -f elasticsearch/master-serviceaccount.yaml
kubectl delete -n it-monitoring -f graylog/serviceaccount.yaml
kubectl delete -n it-monitoring -f graylog/role.yaml
kubectl delete -n it-monitoring -f graylog/rolebinding.yaml
kubectl delete -n it-monitoring -f elasticsearch/client-svc.yaml
kubectl delete -n it-monitoring -f elasticsearch/master-svc.yaml
kubectl delete -n it-monitoring -f mongodb-replicaset/mongodb-service-client.yaml
kubectl delete -n it-monitoring -f mongodb-replicaset/mongodb-service.yaml
kubectl delete -n it-monitoring -f graylog/headless-service.yaml
kubectl delete -n it-monitoring -f graylog/master-service.yaml
kubectl delete -n it-monitoring -f graylog/udp-service.yaml
kubectl delete -n it-monitoring -f graylog/web-service.yaml
kubectl delete -n it-monitoring -f elasticsearch/client-deployment.yaml
kubectl delete -n it-monitoring -f elasticsearch/data-statefulset.yaml
kubectl delete -n it-monitoring -f elasticsearch/master-statefulset.yaml
kubectl delete -n it-monitoring -f mongodb-replicaset/mongodb-statefulset.yaml
kubectl delete -n it-monitoring -f graylog/statefulset.yaml
kubectl delete -n it-monitoring -f graylog/ingress.yaml
