---
# Source: telegraf/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: it-telegraf
  namespace: it-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.32
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: it-telegraf
data:
  telegraf.conf: |+
    
    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2


    [[outputs.influxdb]]
      database = "telegraf"
      username = "$USERNAME"
      password = "$PASSWORD"
      urls = [
        "http://influxdb.it-influxdb:8086"
      ]

    [[inputs.snmp]]
    agents = [ "10.49.0.254:161","10.48.1.1:161","10.48.1.2:161","10.48.1.4:161","10.48.1.5:161","10.49.0.82:161","10.17.0.254:161","10.18.1.200:161"]
      version = 2
      community = "rubinobs"
      name = "snmp"

    [[inputs.snmp.field]]
      name = "hostname"
      oid = "RFC1213-MIB::sysName.0"
      is_tag = true

    [[inputs.snmp.field]]
      name = "temperature"
      oid = ".1.3.6.1.4.1.13742.6.5.5.3.1.4.1.10"

    [[inputs.snmp.table]]
      name = "snmp"
      inherit_tags = [ "hostname" ]
      oid = "IF-MIB::ifXTable"
      [[inputs.snmp.table.field]]
        name = "ifName"
        oid = "IF-MIB::ifName"
        is_tag = true
