---
# Source: telegraf/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: it-telegraf
  namespace: it-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.32
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: it-telegraf