---
# Source: influxdb/templates/post-install-set-auth.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-set-auth
  namespace: it-monitoring
  labels:
    helm.sh/chart: influxdb-4.8.5
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/version: "1.8.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 6
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/instance: influxdb
    spec:
      containers:
      - name: influxdb-set-auth
        image: "appropriate/curl:latest"
        env:
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-credentials
                key: influxdb-user
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-credentials
                key: influxdb-password
        args:
          - "/bin/sh"
          - "-c"
          - |
             curl -X POST http://influxdb:8086/query \
             --data-urlencode \
             "q=CREATE USER \"${INFLUXDB_USER}\" WITH PASSWORD '${INFLUXDB_PASSWORD}' WITH ALL PRIVILEGES"
      restartPolicy: OnFailure
