---
# Source: graylog/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graylog
  namespace: it-monitoring
  labels:
    helm.sh/chart: graylog-1.6.6
    app.kubernetes.io/name: graylog
    app.kubernetes.io/instance: "graylog"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "3.1"
