---
# Source: graylog/charts/mongodb/templates/arbiter/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: graylog-mongodb-arbiter-headless
  namespace: graylog
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.31.2
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: arbiter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-mongodb
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: graylog
    app.kubernetes.io/component: arbiter
