---
# Source: graylog/charts/mongodb-replicaset/templates/mongodb-service-client.yaml
# A headless service for client applications to use
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.11.2
    heritage: Helm
    release: graylog
  name: graylog-mongodb-replicaset-client
  namespace: graylog
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: mongodb-replicaset
    release: graylog
