---
# Source: graylog/charts/elasticsearch/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.2
    component: "master"
    heritage: Helm
    release: graylog
  name: graylog-elasticsearch-discovery
  namespace: graylog
spec:
  clusterIP: None
  ports:
  - port: 9300
    targetPort: transport
  selector:
    app: elasticsearch
    component: "master"
    release: graylog
