{
 "title": "Base to Summit LInk",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Base to Summit Link",
   "type": "graph",
   "gridPos": { "h": 17, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "yaxes": [
    { "format": "decbps" }
   ],
   "targets": [
    {
     "alias": "100G-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 10s) FROM \"snmp\" WHERE (\"agent_host\" = '10.48.1.4' AND \"ifName\" = 'Ethernet1/51') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "TELCONOR - IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "TELCONOR - OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    }
   ]
  },
  {
   "title": "Summit Data Center Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CR_Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.17.0.254" }
     ]
    }
   ]
  },
  {
   "title": "Summit Data Center Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CR_Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.17.0.254" }
     ]
    }
   ]
  },
  {
   "title": "100G Base to Summit",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "100G-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    },
    {
     "alias": "100G-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/51" }
     ]
    }
   ]
  },
  {
   "title": "Telconor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "TELCONOR - IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    },
    {
     "alias": "TELCONOR - OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/48" }
     ]
    }
   ]
  },
  {
   "title": "LHN Monitoring",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "yaxes": [
    { "format": "decbps" }
   ],
   "targets": [
    {
     "alias": "LHN-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    }
   ]
  },
  {
   "title": "LHN Monitoring",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "LHN-01-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-01-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.4" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    },
    {
     "alias": "LHN-02-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.48.1.5" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "Ethernet1/49" }
     ]
    }
   ]
  }
 ]
}